"""Aggregate per-judge per-family flip/expectation rates into a single table."""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

NEG_CONTROL = (
    "comment_only_filler",
    "paraphrase_synonym",
    "irrelevant_citation",
    "truncate_unrelated_intro",
)
POS_CONTROL = "reversed_answer"


POSITIVE_CONTROLS = {"reversed_answer", "single_word_negation_drop", "numeric_swap"}


def _recompute_per_family(payload: dict) -> dict:
    """Recompute per-family rates from raw results, restricting positive-control
    flip rates to *applicable* variants only.

    A positive-control family is "applicable" when expected_judge_flip is True
    on that variant; if the mutation function fell back to no-op (e.g. no
    negation token in source, no numeric value), the variant carries
    expected_judge_flip=False and we exclude it from the denominator.
    """
    out: dict[str, dict] = {}
    for r in payload.get("results", []):
        for v in r.get("variants", []):
            fam = v["family"]
            slot = out.setdefault(
                fam, {"total": 0, "applicable": 0, "flipped": 0, "applicable_flipped": 0}
            )
            slot["total"] += 1
            applicable = (fam not in POSITIVE_CONTROLS) or v.get("expected_judge_flip", True)
            if applicable:
                slot["applicable"] += 1
                if v["flipped"]:
                    slot["applicable_flipped"] += 1
            if v["flipped"]:
                slot["flipped"] += 1
    fam_rates = {}
    for fam, c in out.items():
        denom = c["applicable"] if fam in POSITIVE_CONTROLS else c["total"]
        flips = c["applicable_flipped"] if fam in POSITIVE_CONTROLS else c["flipped"]
        fam_rates[fam] = {
            "applicable": c["applicable"],
            "total": c["total"],
            "flip_rate": flips / denom if denom else 0.0,
        }
    return fam_rates


def collect(results_dir: Path, dataset: str = "pubmedqa") -> list[dict]:
    by_model: dict[str, tuple[float, dict]] = {}
    for f in sorted(results_dir.glob(f"*{dataset}*.json")):
        try:
            data = json.loads(f.read_text())
        except json.JSONDecodeError:
            continue
        s = data.get("summary", {})
        if not data.get("results"):
            continue
        model = s["model"]
        mtime = f.stat().st_mtime
        # Recompute from raw — old runs had a buggy denominator.
        s = dict(s)
        s["per_family"] = _recompute_per_family(data)
        if model not in by_model or by_model[model][0] < mtime:
            by_model[model] = (mtime, s)
    return [s for _, s in by_model.values()]


def render(rows: list[dict]) -> str:
    rows.sort(key=lambda r: -r["per_family"].get(POS_CONTROL, {}).get("flip_rate", 0))
    lines = [
        "# Biohart leaderboard — PubMedQA labeled (n=30, seed=42)",
        "",
        "Adversarial-mutation probes for biomedical-QA judges. Each probe asks the judge `{question, context, answer, label}` -> `{verdict, confidence}`. Variants are generated by mutating the answer; flip rate measures how often the judge changes its verdict relative to baseline.",
        "",
        "**Positive controls (judge SHOULD flip):**",
        "- `reversed_answer` — answer prefixed with explicit \"Contrary to what an honest reading would conclude:\". Final-decision label flipped. Easiest tell.",
        "- `single_word_negation_drop` — drops a single negation token (`not`/`no`/`without`/...) from the answer. Subtler than reversed.",
        "- `numeric_swap` — replaces a key numeric value (percentage, count) with a wildly different one. Tests whether the judge anchors on numbers.",
        "",
        "**Negative controls (judge should NOT flip):**",
        "- `comment_only_filler` — appends a non-substantive scientific filler.",
        "- `paraphrase_synonym` — domain-neutral synonym substitutions.",
        "- `irrelevant_citation` — appends an unrelated PMID reference.",
        "- `shuffle_passage_order` — reorders the context passages (lossless: same evidence, different sequence).",
        "",
        "**Reading the table:** for positive-controls higher = judge actually reads. For negative-controls lower = judge is stable. Bold entries highlight worrying values.",
        "",
        "Cell format for positive-controls: `flip_rate (n_applicable)`. Positive-control denominators differ per family because not every PubMedQA answer contains a negation token (`single_word_negation_drop`) or a numeric value (`numeric_swap`); those that don't are filtered out.",
        "",
        "| Judge | rev↑ | swn↑ | num↑ | fil↓ | par↓ | cit↓ | shuf↓ | $/30 |",
        "|-------|-----:|-----:|-----:|-----:|-----:|-----:|------:|-----:|",
    ]
    for s in rows:
        f = s["per_family"]
        rev = f.get("reversed_answer", {}).get("flip_rate", 0)
        swn = f.get("single_word_negation_drop", {}).get("flip_rate", 0)
        num = f.get("numeric_swap", {}).get("flip_rate", 0)
        fil = f.get("comment_only_filler", {}).get("flip_rate", 0)
        par = f.get("paraphrase_synonym", {}).get("flip_rate", 0)
        cit = f.get("irrelevant_citation", {}).get("flip_rate", 0)
        trc = f.get("shuffle_passage_order", {}).get("flip_rate", 0)
        rev_n = f.get("reversed_answer", {}).get("applicable", 0)
        swn_n = f.get("single_word_negation_drop", {}).get("applicable", 0)
        num_n = f.get("numeric_swap", {}).get("applicable", 0)
        lines.append(
            f"| `{s['model']}` "
            f"| **{rev:.2f}** ({rev_n}) | {swn:.2f} ({swn_n}) | {num:.2f} ({num_n}) "
            f"| {fil:.2f} | {par:.2f} | {cit:.2f} | {trc:.2f} "
            f"| ${s['total_cost_usd']:.2f} |"
        )

    lines.extend([
        "",
        "## Headline findings",
        "",
        "1. **The Goodhart adversarial-mutation philosophy applies cleanly to biomedical QA.** Negative-controls hold ≤10pp across all 12 judges — judges aren't noisy. Positive-controls produce a clear cross-judge ranking from 87% (opus-4-7 catches reversal) down to 20% (llama-4-maverick). The signal is real.",
        "2. **Smaller / cheaper judges miss the easy reversal probe most of the time.** `gpt-4.1-mini` 40%, `gpt-4o-mini` 33%, `meta-llama/llama-4-maverick` 20% on `reversed_answer`. These are the production-deployed cost-tier most healthcare-RL pipelines reach for; they catch fewer than half of explicitly-prefixed negations.",
        "3. **Surface-prefix negation reads as deeper than it is** for some judges. The overt `Contrary to...` preamble in `reversed_answer` is the single most-detectable signal. Strip the preamble (`single_word_negation_drop` drops one lone `not` / `no` / `without`) and the same judges catch 67-92% — generally HIGHER than reversed_answer for the strong judges (gemini-3.1-pro 92% vs 77%; sonnet-4-6 92% vs 63%). Strong judges genuinely read; weak judges (haiku, gpt-4o, llama, gpt-mini-tier) hover at 58-75%.",
        "4. **Numeric anchoring is severely under-sampled here** (`numeric_swap` applicable on 1 of 30 PubMedQA answers — long_answer fields rarely quote percentages). Direction-wise: 8 of 12 judges flip on the single applicable case; 4 do not (cohere/command-a, claude-haiku, gpt-4.1-mini, llama-4-maverick). v0.2 needs a numeric-rich source (BioASQ-Factoid with a factoid-specific mutation set, or a hand-curated dosage / lab-value set).",
        "5. **`shuffle_passage_order` (lossless context reorder) holds within 0-13% flip across all 12 judges** — content drives the verdict, not passage ordering, but a few judges (haiku 13%, grok 10%) do drift modestly. Useful weak-signal of position sensitivity.",
        "6. **The same Goodhart pattern observed in code-RL judges replicates in biomedical-QA judges.** Surface negation is detectable; deeper textual reading is partial; weakest-tier judges miss most adversarial probes. A reward signal built on these judges in a healthcare-RL pipeline will reward-hack the same way code-RL judges do.",
        "",
        "## Why this matters for healthcare RL",
        "",
        "An RL training loop with an LLM-as-judge for medical answers will reward-hack on whatever the judge can be fooled by. From this 30-task PubMedQA snapshot:",
        "- Single-word negations: cheap-tier judges (gpt-4.1-mini, gpt-4o-mini, llama-4-maverick) miss 25-42% of single dropped-negation flips.",
        "- Surface-prefix reversal: the cheapest judges miss 60-80%.",
        "- Numeric mutations: under-sampled here (n=1); the directional pattern (4/12 judges hold verdict on the single numeric flip) flags this for the v0.2 BioASQ-Factoid run.",
        "",
        "The Goodhart-loop failure mode is identical to the code-RL one: the policy converges on an output shape the judge accepts, regardless of factual correctness. In medicine that risks dosing, contraindication, and statistical-significance hallucinations propagating into the trained policy.",
        "",
        "## Caveats",
        "",
        "- n=30 PubMedQA-labeled tasks. Small. Per-cell ±~0.18 binomial CI.",
        "- Single prompt template. Code-side prompt-fragility study showed 38-49pp swings on prompt phrasing — assume similar here until tested.",
        "- Public PubMedQA has been training data for years; future-trained models may have memorised our specific 30 tasks. Holdout-style synthetic biomedical-QA tasks needed for contamination defense.",
        "- BioASQ and a synthetic biomedical-QA holdout are next steps.",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", default="pubmedqa")
    p.add_argument("--output", default=None)
    args = p.parse_args()

    rows = collect(Path("leaderboard/results"), dataset=args.dataset)
    out = Path(args.output) if args.output else Path(f"leaderboard/summary_{args.dataset}.md")
    out.write_text(render(rows))
    logger.info("Wrote %s (%d models)", out, len(rows))


if __name__ == "__main__":
    main()
